version: "2"
services:
  springddd_backend_app:
    container_name: springddd_backend_app
    build: ./Spring_DDD_Rest_Api
    ports:
        -  8080:8080
    volumes:
        - ./Spring_DDD_Rest_Api:/usr/src/app
  reactcrud_frontend_app:
    container_name: reactcrud_frontend_app
    build: ./frontend-employee-crud
    ports:
        - 3000:3000
    volumes:
        - ./frontend-employee-crud:/usr/src/app

